import { ToggleDarkMode } from "@/components/toggleDarkMode";
import type { Metadata } from "next";
import { ThemeProvider } from "next-themes";
import { Geist_Mono, Tinos } from "next/font/google";
import "./globals.css";

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const tinos = Tinos({
  weight: ["400", "700"],
  subsets: ["latin", "latin-ext"],
  variable: "--font-tinos",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${tinos.variable} ${geistMono.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col">
        <ThemeProvider attribute="class">
          <header>
            <div className="ml-1.5 mt-1.5">
              <ToggleDarkMode />
            </div>
          </header>

          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
